## 2.1 Data Manipulation

Generally, there are two important things we need to do with data: (i) acquire them; and (ii) process them once they are inside the computer. 

we use n-dimesnional array which is also called the tensor to store data. 
a tensor represets array of numerical values
with one axis, a tensor corresponds to a vector
with two axes, a tensor corresponds to a matrix
tensors with more than two axes do not have special name. 
each values in a tensor is called element of the tensor. 

Unless otherwise specified a new tensors will be stored in main memory and designated for CPU-based computation. 
    

In [1]:
import torch
#arange creates a row vector x containing the first 12 integers starting from 0. 
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
#access tensor's shape by inspecting it's shape property
x.shape

torch.Size([12])

In [3]:
#to know the total number of elements in a tensor 
x.numel()

12

In [4]:
#change the shape of the tensor without altering the number of elements or their values, invoke reshape function
X=x.reshape(3,4)
X
# x.reshape(3, 4) is equivalent to  x.reshape(-1, 4) or x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
#create a tensor representing a tensor with all elements set to 0 and a shape of (2, 3, 4)
torch.zeros(2,3,4)
#similarly a tensor with ones can be created with torch.ones(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
#elements are randomly sampled from a standard Gaussian distribution with a mean of 0 and standard deviation of 1
torch.randn(2,3,4)

tensor([[[-1.0332,  0.5729,  1.7230,  0.4498],
         [-0.3705,  0.1873, -0.0696, -1.3813],
         [ 1.7296,  0.5564, -1.5853,  0.3685]],

        [[ 0.9239,  0.7719,  0.4398,  0.4306],
         [ 0.0485, -1.3356, -0.9727, -0.4116],
         [-0.8240, -2.2423,  0.6086,  0.2774]]])

In [7]:
#exact values of elements can be specified in desired shape by supplying a python list. 
torch.tensor([[1,2,3,4],[2,3,4,5],[3,4,5,6]])


tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]])

Elementwise operations apply a standard scalar operation to each element of an array. For functions that take two arrays as inputs, elementwise operations apply some standard binary operator on each pair of corresponding elements from the two arrays.
The common standard arithmetic operators (+, -, *, /, and ** ) have all been lifted to elementwise operations for any identically-shaped tensors of arbitrary shape. We can call elementwise operations on any two tensors of the same shape. 


In [8]:
x = torch.tensor([4, 2.1, 3, 5])
y = torch.tensor([2, 3, 2, 3])
x + y, x - y, x * y, x / y, x ** y

(tensor([6.0000, 5.1000, 5.0000, 8.0000]),
 tensor([ 2.0000, -0.9000,  1.0000,  2.0000]),
 tensor([ 8.0000,  6.3000,  6.0000, 15.0000]),
 tensor([2.0000, 0.7000, 1.5000, 1.6667]),
 tensor([ 16.0000,   9.2610,   9.0000, 125.0000]))

In addition to elementwise computations, we can also perform linear algebra operations, including vector dot products and matrix multiplication. 

In [9]:
#concatenate multiple tensors together, stacking them end-to-end to form a larger tensor.
#provide a list of tensors and tell the system along which axis to concatenate.
x=torch.arange(12, dtype=torch.float32).reshape((3,4))
y=torch.tensor([[2,3.0,4,5],[1,3,5,7],[5,7,9,11]])
torch.cat((x,y), dim=0), torch.cat((x,y), dim=1)
#dim=0 concatenate two matrices along rows
#dim=1 concatenate two matrices along columns


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  3.,  4.,  5.],
         [ 1.,  3.,  5.,  7.],
         [ 5.,  7.,  9., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  3.,  4.,  5.],
         [ 4.,  5.,  6.,  7.,  1.,  3.,  5.,  7.],
         [ 8.,  9., 10., 11.,  5.,  7.,  9., 11.]]))

In [10]:
# For each position, if X and Y are equal at that position, the corresponding entry in the new tensor takes a value of 1,
#otherwise that position takes 0.
x==y

tensor([[False, False, False, False],
        [False, False, False,  True],
        [False, False, False,  True]])

In [11]:
#Summing all the elements in the tensor yields a tensor with only one element.
x.sum()

tensor(66.)

Even when shapes differ, we can still perform elementwise operations by invoking the broadcasting mechanism. 
This mechanism works in the following way: First, expand one or both arrays by copying elements appropriately so that after this transformation, the two tensors have the same shape. Second, carry out the elementwise operations on the resulting arrays.

In [12]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(4).reshape(1,4)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2, 3]]))

Since a and b are  3×1  and  1×4  matrices respectively, their shapes do not match up if we want to add them. We broadcast the entries of both matrices into a larger  3×4  matrix as follows: for matrix a it replicates the columns and for matrix b it replicates the rows before adding up both elementwise.

In [13]:
a+b

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])

elements in a tensor can be accessed by index.the first element has index 0 and ranges are specified to include the first but before the last element. we can access elements according to their relative position to the end of the list by using negative indices.

In [14]:
#[-1] selects the last element
x[-1]


tensor([ 8.,  9., 10., 11.])

In [15]:
#[1:3] selects the second and the third elements 
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
#Beyond reading, we can also write elements of a matrix by specifying indices.
x[1,3]=22
x[1]

tensor([ 4.,  5.,  6., 22.])

If we want to assign multiple elements the same value, we simply index all of them and then assign them the value. For instance, [0:2, :] accesses the first and second rows, where : takes all the elements along axis 1 (column). While we discussed indexing for matrices, this obviously also works for vectors and for tensors of more than 2 dimensions.

In [17]:
x=torch.arange(12).reshape(3,4)
x
x[0:2, 0:2]=10
x

tensor([[10, 10,  2,  3],
        [10, 10,  6,  7],
        [ 8,  9, 10, 11]])

Saving Memory
if we write Y = X + Y, we will dereference the tensor that Y used to point to and instead point Y at the newly allocated memory. After running Y = Y + X, we will find that id(Y) points to a different location. That is because Python first evaluates Y + X, allocating new memory for the result and then makes Y point to this new location in memory.

In [18]:
before=id(y)
y=y+x
id(y)==before

False

To perform in-place operations, assign the result of an operation to a previously allocated array with slice notation, e.g., Y[:] = <expression>. To illustrate this concept, we first create a new matrix Z with the same shape as another Y, using zeros_like to allocate a block of  0  entries.

In [19]:
z=torch.zeros_like(y)
z
print('id(z): ', id(z))
z[:]=x+y
print('id(z): ', id(z))
#X[:] = X + Y is same as X += Y 

id(z):  1993719816664
id(z):  1993719816664


Conversion to other python objects


In [20]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [21]:
#To convert a size-1 tensor to a Python scalar, we can invoke the item function or Python’s built-in functions.
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### Exercises

In [22]:
#1. Change the conditional statement X == Y in this section to X < Y or X > Y, and then see what kind of tensor you can get.
x=torch.arange(15).reshape(3,5)
y=torch.tensor([[1,3,5,7,9],[2,4,6,8,0],[2,3,4,5,6]])
x, y, x<y, x>y

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]),
 tensor([[1, 3, 5, 7, 9],
         [2, 4, 6, 8, 0],
         [2, 3, 4, 5, 6]]),
 tensor([[ True,  True,  True,  True,  True],
         [False, False, False, False, False],
         [False, False, False, False, False]]),
 tensor([[False, False, False, False, False],
         [ True,  True,  True, False,  True],
         [ True,  True,  True,  True,  True]]))

In [23]:
#Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, eg., 3-dimensional tensors. 
#Is the result the same as expected?
a=torch.arange(6).reshape(2,1,3)
b=torch.arange(4).reshape(2,2,1)
a,b, a+b

#while adding two 3-d tensors of different shapes, either each dimension of one tensor should be one or same as the other tensor. 


(tensor([[[0, 1, 2]],
 
         [[3, 4, 5]]]),
 tensor([[[0],
          [1]],
 
         [[2],
          [3]]]),
 tensor([[[0, 1, 2],
          [1, 2, 3]],
 
         [[5, 6, 7],
          [6, 7, 8]]]))

## 2.2 Data Preprocessing
preprocessing raw data with pandas and converting them into the tensor format. 

Reading the data set


In [24]:
import pandas as pd
data =pd.read_csv("Career_Stats_Passing.csv")
data.head(0)

Empty DataFrame
Columns: [Player Id, Name, Position, Year, Team, Games Played, Passes Attempted, Passes Completed, Completion Percentage, Pass Attempts Per Game, Passing Yards, Passing Yards Per Attempt, Passing Yards Per Game, TD Passes, Percentage of TDs per Attempts, Ints, Int Rate, Longest Pass, Passes Longer than 20 Yards, Passes Longer than 40 Yards, Sacks, Sacked Yards Lost, Passer Rating]
Index: []

[0 rows x 23 columns]

Handling missing data. "NaN" entries are missing values. To handle missing data, typical methods include imputation and deletion, where imputation replaces missing values with substituted ones, while deletion ignores missing values. 

Imputation


## Exercises


In [25]:
# 1. Delete the column with the most missing values.

a=[list(dict(data.isna().sum()).values()).index(max(data.isna().sum()))]
a
data.drop(data.columns[a], axis=1, inplace=True)
data.head(0)

Empty DataFrame
Columns: [Player Id, Name, Year, Team, Games Played, Passes Attempted, Passes Completed, Completion Percentage, Pass Attempts Per Game, Passing Yards, Passing Yards Per Attempt, Passing Yards Per Game, TD Passes, Percentage of TDs per Attempts, Ints, Int Rate, Longest Pass, Passes Longer than 20 Yards, Passes Longer than 40 Yards, Sacks, Sacked Yards Lost, Passer Rating]
Index: []

[0 rows x 22 columns]

Convert the preprocessed dataset to the tensor format.

## 2.3 Linear Algebra


In [26]:
#Matrices
A=torch.arange(25).reshape(5,5)
A, A.T, A==A.T

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]]),
 tensor([[ 0,  5, 10, 15, 20],
         [ 1,  6, 11, 16, 21],
         [ 2,  7, 12, 17, 22],
         [ 3,  8, 13, 18, 23],
         [ 4,  9, 14, 19, 24]]),
 tensor([[ True, False, False, False, False],
         [False,  True, False, False, False],
         [False, False,  True, False, False],
         [False, False, False,  True, False],
         [False, False, False, False,  True]]))

Tensors
given any two tensors with the same shape, the result of any binary elementwise operation will be a tensor of that same shape. 


In [27]:
x=3
t1=torch.arange(20).reshape(2,2,5)
t1+x, (t1*x).shape

(tensor([[[ 3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12]],
 
         [[13, 14, 15, 16, 17],
          [18, 19, 20, 21, 22]]]),
 torch.Size([2, 2, 5]))

In [28]:
#Reduction
#One useful operation that we can perform with arbitrary tensors is to calculate the sum of their elements.
m2=torch.arange(12, dtype=torch.float32).reshape(3,4)
m2, m2.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor(66.))

In [29]:
#To reduce the row dimension (axis 0) by summing up elements of all the rows, we specify axis=0 when invoking the function. 
m2_sum_axis0=m2.sum(axis=0)
m2_sum_axis0, m2_sum_axis0.shape

(tensor([12., 15., 18., 21.]), torch.Size([4]))

In [30]:
#Specifying axis=1 will reduce the column dimension (axis 1) by summing up elements of all the columns.
m2_sum_axis1=m2.sum(axis=1)
m2_sum_axis1, m2_sum_axis1.shape

(tensor([ 6., 22., 38.]), torch.Size([3]))

In [31]:
#Reducing a matrix along both rows and columns via summation is equivalent to summing up all the elements of the matrix.
m2_sum=m2.sum(axis=[0,1])
m2_sum, m2_sum.shape

(tensor(66.), torch.Size([]))

In [32]:
#the function for calculating the mean can also reduce a tensor along the specified axes
m2_mean_axis0=m2.mean(axis=0)
m2_mean_axis0, m2.sum(axis=0)/m2.shape[0]

(tensor([4., 5., 6., 7.]), tensor([4., 5., 6., 7.]))

In [33]:
m2_mean_axis1=m2.mean(axis=1)
m2_mean_axis1, m2.sum(axis=1)/m2.shape[1]

(tensor([1.5000, 5.5000, 9.5000]), tensor([1.5000, 5.5000, 9.5000]))

In [34]:
#non-reduction sum
#sometimes it can be useful to keep the number of axes unchanged when invoking the function for calculating the sum or mean.
m2_sum_axis0=m2.sum(axis=0, keepdims=True)
m2_sum_axis1=m2.sum(axis=1, keepdims=True)
m2, m2_sum_axis0, m2_sum_axis0.shape, m2_sum_axis1, m2_sum_axis1.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[12., 15., 18., 21.]]),
 torch.Size([1, 4]),
 tensor([[ 6.],
         [22.],
         [38.]]),
 torch.Size([3, 1]))

In [35]:
#dot product
#Given two vectors  x,y, their dot product is a sum over the products of the elements at the same position.
p=torch.arange(4, dtype=torch.float32)
q=torch.arange(4, dtype=torch.float32)
p, q, torch.dot(p,q), torch.sum(p*q)

(tensor([0., 1., 2., 3.]), tensor([0., 1., 2., 3.]), tensor(14.), tensor(14.))

In [36]:
#matrix-vector products
#When we call np.dot(A, x) with a matrix A and a vector x, the matrix-vector product is performed.
#the column dimension of A (its length along axis 1) must be the same as the dimension of x (its length)
m2, m2.shape, p, p.shape, torch.mv(m2, p)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]),
 tensor([0., 1., 2., 3.]),
 torch.Size([4]),
 tensor([14., 38., 62.]))

In [37]:
#matrix-matrix multiplication
m1=torch.clone(m2)
m1=m1.reshape(4,3)
m1.shape, m2.shape, torch.mm(m1,m2), torch.mm(m1,m2).shape


(torch.Size([4, 3]),
 torch.Size([3, 4]),
 tensor([[ 20.,  23.,  26.,  29.],
         [ 56.,  68.,  80.,  92.],
         [ 92., 113., 134., 155.],
         [128., 158., 188., 218.]]),
 torch.Size([4, 4]))

In [38]:
#norms
#the norm of a vector tells us how big a vector is.
#The  L2  norm of vector x  is the square root of the sum of the squares of the vector elements.
#L1  norm, which is expressed as the sum of the absolute values of the vector elements
u=torch.tensor([3.0, -4.0])
torch.norm(u), torch.abs(u).sum()

(tensor(5.), tensor(7.))

In [39]:
#Both the  L2  norm and the  L1  norm are special cases of the more general  Lp  norm
# is the square root of the sum of the squares of the matrix elements
torch.norm(torch.ones((4, 9)))

tensor(6.)

## Exercises

In [40]:
# 1. Prove that the transpose of a matrix  A’s transpose is  A.
#d1=Transpose of m1, d2=transpose of transpose of m1
d1=m1.T
d2=d1.T
m1==d2, m1.shape, d2.shape
#Hence proved

(tensor([[True, True, True],
         [True, True, True],
         [True, True, True],
         [True, True, True]]),
 torch.Size([4, 3]),
 torch.Size([4, 3]))

In [41]:
# 2. Given two matrices  A  and  C , show that the sum of transposes is equal to the transpose of a sum.
A.shape
C=torch.ones(5,5)
AT=A.T
CT=C.T
AT+CT==(A+C).T
#Hence Proved

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [42]:
# 3. Given any square matrix  A, sum of A and A transpose is always symmetric. Why?
#Symmetric matrix is a square matrix that is equal to its transpose
SY=A+AT
SY==SY.T

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [45]:
# 4. We defined the tensor Z of shape (2, 3, 4) in this section. What is the output of len(Z)?
# The length of a vector is commonly called the dimension of the vector.
Z=torch.arange(24).reshape(2,3,4)
len(Z)
#len(Z) is 2

3